# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Mon Sep  5 14:44:01 2016
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(735, 509)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Pictures/callum.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, 10, 200)
        self.verticalLayout.setObjectName("verticalLayout")
        self.XView = QtWidgets.QRadioButton(self.centralWidget)
        self.XView.setObjectName("XView")
        self.verticalLayout.addWidget(self.XView)
        self.YView = QtWidgets.QRadioButton(self.centralWidget)
        self.YView.setObjectName("YView")
        self.verticalLayout.addWidget(self.YView)
        self.ZView = QtWidgets.QRadioButton(self.centralWidget)
        self.ZView.setObjectName("ZView")
        self.verticalLayout.addWidget(self.ZView)
        self.Bore = QtWidgets.QRadioButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bore.sizePolicy().hasHeightForWidth())
        self.Bore.setSizePolicy(sizePolicy)
        self.Bore.setObjectName("Bore")
        self.verticalLayout.addWidget(self.Bore)
        self.AverageBore = QtWidgets.QRadioButton(self.centralWidget)
        self.AverageBore.setObjectName("AverageBore")
        self.verticalLayout.addWidget(self.AverageBore)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 3, 2, 1)
        self.Scroll_Horz = QtWidgets.QScrollBar(self.centralWidget)
        self.Scroll_Horz.setOrientation(QtCore.Qt.Horizontal)
        self.Scroll_Horz.setObjectName("Scroll_Horz")
        self.gridLayout_2.addWidget(self.Scroll_Horz, 1, 2, 1, 1)
        self.Scroll_Vert = QtWidgets.QScrollBar(self.centralWidget)
        self.Scroll_Vert.setOrientation(QtCore.Qt.Vertical)
        self.Scroll_Vert.setObjectName("Scroll_Vert")
        self.gridLayout_2.addWidget(self.Scroll_Vert, 0, 0, 1, 1)
        self.mplwindow = QtWidgets.QWidget(self.centralWidget)
        self.mplwindow.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwindow.sizePolicy().hasHeightForWidth())
        self.mplwindow.setSizePolicy(sizePolicy)
        self.mplwindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mplwindow.setObjectName("mplwindow")
        self.mplvl = QtWidgets.QVBoxLayout(self.mplwindow)
        self.mplvl.setContentsMargins(0, 0, 0, 0)
        self.mplvl.setObjectName("mplvl")
        self.gridLayout_2.addWidget(self.mplwindow, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 735, 25))
        self.menuBar.setObjectName("menuBar")
        self.menu_Menu = QtWidgets.QMenu(self.menuBar)
        self.menu_Menu.setObjectName("menu_Menu")
        self.menuSettings = QtWidgets.QMenu(self.menu_Menu)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.Open = QtWidgets.QAction(MainWindow)
        self.Open.setObjectName("Open")
        self.Reset = QtWidgets.QAction(MainWindow)
        self.Reset.setObjectName("Reset")
        self.AutoScale = QtWidgets.QAction(MainWindow)
        self.AutoScale.setCheckable(True)
        self.AutoScale.setObjectName("AutoScale")
        self.menuSettings.addAction(self.AutoScale)
        self.menu_Menu.addAction(self.Open)
        self.menu_Menu.addAction(self.Reset)
        self.menu_Menu.addAction(self.menuSettings.menuAction())
        self.menuBar.addAction(self.menu_Menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Data Cube Viewer"))
        self.XView.setText(_translate("MainWindow", "X View"))
        self.YView.setText(_translate("MainWindow", "Y View"))
        self.ZView.setText(_translate("MainWindow", "Z View"))
        self.Bore.setText(_translate("MainWindow", "Draw Bore"))
        self.AverageBore.setText(_translate("MainWindow", "Avg. Bore"))
        self.menu_Menu.setTitle(_translate("MainWindow", "&Menu"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.Open.setText(_translate("MainWindow", "&Open"))
        self.Open.setToolTip(_translate("MainWindow", "Open a file"))
        self.Open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.Reset.setText(_translate("MainWindow", "&Reset"))
        self.Reset.setToolTip(_translate("MainWindow", "Reset"))
        self.Reset.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.AutoScale.setText(_translate("MainWindow", "AutoScale"))
        self.AutoScale.setToolTip(_translate("MainWindow", "AutoScale colourbars"))

